
#ifndef OPCODES_H
#define OPCODES_H


enum class OpCode
{
    MSG_NULL,
    MSG_OPENLIVE,
    MSG_SYSTEM,
    MSG_CONNECTED,
    MSG_RECORDDATA,
    MSG_GETRECORDDATA,
    MSG_FAILRECORDDATA,
    MSG_RECORDRESULT,
    MSG_ID_GETUSERINFO,
    MSG_ID_SETUSERINFO,
    MSG_DELRECORDDATA,
    MSG_INSRECORDDATA,
    MSG_ISRECORDDATA,
    MSG_WHISPERMESSAGE,
    MSG_CHECK_NETSTATE,
    MSG_AUTH_ADMIN_MODE,
    MSG_SET_OBJSERIAL,
    MSG_CHECK_NETSTATE2,
    MSG_CHECK_NETSTATE3,
    MSG_CHECK_NETSTATE4,
    MSG_CHECK_NETSTATE5,
    MSG_IPLIST,
    MSG_CHATMESSAGE,
    MSG_END
};


#endif // OPCODES_H
